/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Poppins', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['"Hanken Grotesk"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        'surface': 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-dim': 'rgb(var(--color-surface-dim) / <alpha-value>)',
        'surface-bright': 'rgb(var(--color-surface-bright) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        'outline': 'rgb(var(--color-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--color-outline-variant) / <alpha-value>)',
        'primary': 'rgb(var(--color-primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--color-primary) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--color-on-primary) / <alpha-value>)',
        'secondary': '#34d399',
        'on-secondary': '#000000',
        'error': '#fca5a5',
        'on-error': '#450a0a',
        'error-container': '#7f1d1d',
        'on-error-container': '#fecaca',
        'primary-fixed': 'rgb(var(--color-primary) / <alpha-value>)',
        'status-success': 'rgb(var(--color-status-success) / <alpha-value>)',
        'status-success-on': 'rgb(var(--color-status-success-on) / <alpha-value>)',
        'status-ready': 'rgb(var(--color-status-ready) / <alpha-value>)',
        'status-ready-on': 'rgb(var(--color-status-ready-on) / <alpha-value>)',
        'status-warning': 'rgb(var(--color-status-warning) / <alpha-value>)',
        'status-warning-on': 'rgb(var(--color-status-warning-on) / <alpha-value>)',
        'status-danger': 'rgb(var(--color-status-danger) / <alpha-value>)',
        'status-danger-on': 'rgb(var(--color-status-danger-on) / <alpha-value>)',
        'status-info': 'rgb(var(--color-status-info) / <alpha-value>)',
        'status-info-on': 'rgb(var(--color-status-info-on) / <alpha-value>)',
        'status-progress': 'rgb(var(--color-status-progress) / <alpha-value>)',
        'status-progress-on': 'rgb(var(--color-status-progress-on) / <alpha-value>)',
      }
    },
  },
  plugins: [],
}
