export const defaultTasks = [
  {
    id: 1,
    text: 'Recruit specialized "Canvas-Stretcher" (Gallery Wrap expert)',
    completed: false,
    category: "HR",
  },
  {
    id: 2,
    text: 'Print "Print To Frame Partner Packs" (50 cards + Steel/Canvas Samples)',
    completed: false,
    category: "Marketing",
  },
  {
    id: 3,
    text: "Secure 1,000 sq ft workshop (Kadawatha/Peliyagoda)",
    completed: false,
    category: "Operations",
  },
  {
    id: 4,
    text: "Stock 1.2mm Box Bars (Bulk purchase 50 lengths)",
    completed: false,
    category: "Inventory",
  },
  {
    id: 5,
    text: "Visit 10 Digital Art Printers in Nugegoda/Maharagama",
    completed: false,
    category: "Sales",
  },
];

export const defaultCustomers = [
  {
    nic: "901234567V",
    type: "Individual",
    businessName: "",
    name: "Amal Perera",
    phone: "0771234567",
    email: "amal@test.com",
    orders: 2,
  },
  {
    nic: "857654321V",
    type: "Business",
    businessName: "Silva Constructions",
    name: "Kamani Silva",
    phone: "0719876543",
    email: "kamani@silvaconstruct.com",
    orders: 5,
  },
  {
    nic: "199550010020",
    type: "Individual",
    businessName: "",
    name: "Ruwan Dias",
    phone: "0765551234",
    email: "ruwan@test.com",
    orders: 1,
  },
];

export const defaultPartners = [
  {
    id: 1,
    partnerId: "P-1001",
    name: "PixelPerfect Design",
    type: "Agency",
    totalSqFt: 1200,
    paid: 25000,
    pending: 5000,
    googleLink: "https://maps.google.com/?q=PixelPerfect",
    socialLink: "https://instagram.com/pixelperfect",
  },
  {
    id: 2,
    partnerId: "P-1002",
    name: "City Prints Nugegoda",
    type: "Printer",
    totalSqFt: 3400,
    paid: 80000,
    pending: 5000,
    googleLink: "",
    socialLink: "",
  },
  {
    id: 3,
    partnerId: "P-1003",
    name: "Creative Hive",
    type: "Freelancer",
    totalSqFt: 400,
    paid: 5000,
    pending: 5000,
    googleLink: "",
    socialLink: "https://facebook.com/creativehive",
  },
];

export const defaultProjects = [
  {
    jobNo: "J-24-001",
    clientNIC: "901234567V",
    partnerId: "P-1001",
    deadline: "2024-12-30",
    scope: "Large Digital Art Frame (8x5) - Gallery Wrap",
    materials: "1.2mm Box Bars, Zinc-Alum Priming",
    note: "High tension wrap required for digital art.",
    address: "No 55, Galle Road, Colombo 03",
    assignee: "Saman (Master Welder)",
    status: "Ongoing",
    flexReceived: true,
    value: 85000,
    totalSqFt: 40,
  },
  {
    jobNo: "J-24-002",
    clientNIC: "857654321V",
    partnerId: "P-1002",
    deadline: "2025-01-05",
    scope: "Set of 5 Canvas Frames for Studio",
    materials: "1 inch Square Tube, Matte Black",
    note: "Check corner squareness accurately.",
    address: "City Prints Warehouse, Nugegoda",
    assignee: "Kamal (Assistant)",
    status: "Pending",
    flexReceived: false,
    value: 55000,
    totalSqFt: 25,
  },
];

export const defaultLogistics = [
  {
    id: "L-PK-001",
    type: "Pickup",
    subType: "Printed Canvas",
    location: "Melwa Steel, Peliyagoda",
    status: "Pending",
    startTime: null,
    endTime: null,
    duration: null,
    manifest: null,
  },
  {
    id: "L-DL-001",
    type: "Delivery",
    subType: "Finished Frames",
    location: "Silva Constructions Site, Battaramulla",
    status: "Completed",
    startTime: new Date(Date.now() - 3600000).toISOString(),
    endTime: new Date().toISOString(),
    duration: "1h 0m",
    manifest: "delivery_slip.jpg",
  },
];

export const defaultLeads = [
  {
    id: "L-001",
    name: "Nimal Sirisena",
    company: "Nimal Homes",
    phone: "0773334445",
    email: "nimal@homes.lk",
    value: 150000,
    stage: "Intake",
    source: "Referral",
    agentId: "P-1001",
    date: "2024-12-15",
    jobScope: "5 Canvas frames (24x36)",
    deliveryLocation: "123 Kandy Rd, Kadawatha",
    quotationGenerated: false,
  },
  {
    id: "L-002",
    name: "Sunil Perera",
    company: "Sunil Digital Art",
    phone: "0714445556",
    email: "sunil@digital.lk",
    value: 85000,
    stage: "Deal",
    source: "Social Media",
    date: "2024-12-20",
    jobScope: "Large Digital Art Frame (8x5) - Gallery Wrap",
    deliveryLocation: "City Prints Warehouse, Nugegoda",
    quotationGenerated: true,
  },
  {
    id: "L-003",
    name: "Kasun Jayawardena",
    company: "Gallery Wall",
    phone: "0765556667",
    email: "kasun@gallery.lk",
    value: 200000,
    stage: "Processing",
    source: "Referral",
    agentId: "P-1002",
    date: "2024-12-22",
    jobScope: "Set of 10 identical gallery frames for new hotel",
    deliveryLocation: "Gallery Wall main office",
    quotationGenerated: false,
  },
];

export const defaultInvoices = [
  {
    id: "INV-1001",
    leadId: "L-003",
    customerName: "Kasun Jayawardena",
    company: "Gallery Wall",
    date: "2024-12-23",
    amount: 150000,
    status: "Unpaid",
    aiDraft: `# Invoice\n\n- 75% Advance for 10 gallery frames`,
  },
];
